More support for the  GeoNode v2 API
kartoza/qgis_geonode pull request #10
Opened 2020-12-31 14:41 UTC by Samweli

Work for https://github.com/kartoza/qgis_geonode/issues/1

Use cases that have been covered in this PR

- [x] get a paginated list of existing layers
- [x] get a paginated list of existing maps
- [x] get individual layer details
- [ ] get layer's metadata fields, as suitable for using in QGIS layer metadata 
- [x] get a list of layer's styles with their respective SLD definition
- [ ] identify the layer's default style

@ricardogsilva I could not find API endpoint in the GeoNode v2 API that directly provide layer's metadata fields and an endpoint that provides layer's default styles.

2020-12-31 16:14 UTC, ricardogsilva requested changes
Nice work overall.

I like your solution of bundling the signal that needs to be emitted together with the other arguments to `self.response_fetched()` :+1: 

There are somethings I'd like you to change before merging though. Please work on them. Most of them are in inline comments.

Additional feedback:

- I can merge this PR after you do the changes requested, but please focus on adding unit tests immediately after it has been merged
- Please do not include empty `__init__.py` files in a PR

2020-12-31 16:14 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/api_client.py
> +    def run_task(self, request, handler):
Please rename the `handler` argument to `signal_to_emit`.

2020-12-31 16:14 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/api_client.py
> +    def response_fetched(self, task: QgsNetworkContentFetcherTask, signal_handler: pyqtSignal):
Please rename `signal_handler` argument to `signal_to_emit`

2020-12-31 16:14 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/api_client.py
> +    MAP_LIST = "/api/v2/maps/"
Your proposed implementation does not use this enum anymore, so please remove it

2020-12-31 16:14 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/api_client.py
> +        self.run_task(request, signal_handler)
please condense these two lines into one, as there is no need for the `signal_handler` variable to exist (it will not be used again) - do the same for the other methods

2020-12-31 16:14 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/api_client.py
>              QUrl(f"{self.base_url}{GeonodeApiEndpoint.LAYER_LIST.value}"))
Contrary to what is said on the PR description, I see no support for pagination here.

That is fine, you don't need to add support for pagination in this PR (lets leave that for the future) but please do not make the claim that it is being supported here, as that may make it harder to review the work later on. This also applies to the styles and maps list endpoints, where none are paginated

2021-01-04 10:16 UTC, Samweli commented on src/qgis_geonode/apiclient/api_client.py
> +    MAP_LIST = "/api/v2/maps/"
@ricardogsilva I think in the implementation I'm using each of these enums.

2021-01-04 10:39 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/api_client.py
> +    MAP_LIST = "/api/v2/maps/"
Apologies, I think I didn't explain my point correctly. 

What I mean is that in the previous state I was using this enum to retrieve the endpoint after the response had been received and then I was deriving the signal to be emitted from that.

In your PR you now send the signal to be emitted to the method that handles the HTTP response (which seems like a nice approach), so there is no need to guess what the signal is anymore. This means that the enum is not needed now.

I see you are using it to get the GeoNode endpoint URIs, but IMO those are now just an internal implementation detail of the `GeoNodeClient` class and they don't need to be exposed outside of it.

My suggestion is that you hardcode the endpoints inside their respective method caller and get rid of the enum. But anyway, if you feel against this, please use your best judgment ;)

2021-01-04 12:48 UTC, Samweli commented on src/qgis_geonode/apiclient/api_client.py
>              QUrl(f"{self.base_url}{GeonodeApiEndpoint.LAYER_LIST.value}"))
noted @ricardogsilva

2021-01-04 12:56 UTC, Samweli commented on src/qgis_geonode/apiclient/api_client.py
> +    MAP_LIST = "/api/v2/maps/"
okay I would like to keep them.

2021-01-04 18:22 UTC, ricardogsilva approved these changes
Thanks @samweli

2021-01-04 18:22 UTC, merged