Vector sld handling
kartoza/qgis_geonode pull request #109
Opened 2021-02-18 07:03 UTC by Samweli

Fixes https://github.com/kartoza/qgis_geonode/issues/90

Adds support for loading sld style used in the GeoNode instance to the loaded QGIS vector layer.

2021-02-18 10:37 UTC, ricardogsilva requested changes
A couple of extra comments in addition to the ones included inline:

- I've recently fixed a bug in the CI pipeline. It is now enforcing that the code is formatted according to black's rule. That is why the github checks are failing. Be sure to run your PR through black in order to get the check to pass before I will be OK with merging this

- The ultimate goal of what we are trying to achieve with this PR is to be able to load SLD styles for vector layers with the current version of the GeoNode V2 API. This PR does not fulfill that goal. When I load a WFS layer from GeoNode I get this error:

  **Problem in downloading style for the layer, ['Download failed: Host geoserver not found']**

  This error happens because of this issue geosolutions-it/nexus-geonode#20. Regardless, we shall try to load the SLD by guessing the correct URL, the same way we are currently doing with the WMS/WFS URLs. Otherwise we cannot really test if the code works OK. Please parse the API response of the SLD URL and replace the internal geoserver address with the public one for the layer, which should be `{geonode-base-url}/geoserver/{remaininig SLD URL}`

2021-02-18 10:37 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/apiv2.py
> +    )
This code is flawed. You try to get the default style and if not available it defaults to an empty string. Then you proceed to use the `dict.get()` method on it as if it is always a dict. If it is a string this will crash.

Lets assume there will always be a default style for all layers, as I can't think of a case where that would not be true.


```suggestion
    default_style = models.BriefGeonodeStyle(
        pk=deserialized_resource["default_style"]["pk"],
        name=deserialized_resource["default_style"]["name"],
        sld_url=deserialized_resource["default_style"]["sld_url"]
    )
```

2021-02-18 10:37 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/apiv2.py
> +            sld_url=item.get("sld_url"))
No point in using `item.get("key")` here since we expect styles to be well-formed and there is no meaning in having a style without name or url. Use `item["key"]` instead and if there is an error that means the response was malformed, we crash

2021-02-18 10:37 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/models.py
> +        self.pk = pk
Let's not store the `pk` property of the style until we can anticipate that we will need it for something. 

For the moment I can't imagine why we would need it, and as a general practice we should not hold on to values that are not used, as these may cause our code to break in the future (for example if the GeoNode devs decide to remove the `pk` property from the style API response, we would get an error on our side with something we don't even need to have)

2021-02-18 10:37 UTC, ricardogsilva commented on src/qgis_geonode/gui/layer_properties_config_widget.py
> +               (layer.type() == QgsMapLayerType.RasterLayer)
This seems more idiomatic:

```suggestion
        return layer.type() in (QgsMapLayerType.VectorLayer, QgsMapLayerType.RasterLayer)
```

2021-02-18 10:37 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +
This approach involves saving the SLD to a temp file on disk and then loading it into the layer. Lets try to avoid the extra IO of saving/reading from disk and directly use the style as returned from the URL.

Instead of a `QFileDownloader`, use a `QgsNetworkContentFetcherTask`. This is the same approach we are using in `apiclient.apiv2`.

Make a GET request, get back the SLD body, which is an XML document, and then use Qt's XML facilities to parse the response body into a `QDomNode`.

For loading the SLD, instead of `QgsMapLayer.loadSldStyle`, use [QgsMapLayer.readSld](https://qgis.org/api/classQgsMapLayer.html#ab7fcb070c317b3cb4853f11ea8ce3afd). This expects a `QDomNode` as an input, so it will likely work OK.

2021-02-18 14:02 UTC, Samweli commented on src/qgis_geonode/apiclient/apiv2.py
> +            sld_url=item.get("sld_url"))
> we crash

right :laughing:

2021-02-18 14:09 UTC, Samweli commented
> * Otherwise we cannot really test if the code works OK

I did test the code logic by using some urls pointing to different slds and it worked!

2021-02-18 14:16 UTC, ricardogsilva commented
> I did test the code logic by using some urls pointing to different slds and it worked!

As much as I believe you, we also need to actually see it working with the V2 API :wink:

2021-02-18 14:19 UTC, Samweli commented
> As much as I believe you, we also need to actually see it working with the V2 API

:smile:

2021-02-21 08:56 UTC, Samweli commented
Hi @ricardogsilva, I have address your comments in the review, one thing remaining is the sld styles are not able to load in the vector layer using the [QgsMapLayer.readSld](https://qgis.org/api/classQgsMapLayer.html#ab7fcb070c317b3cb4853f11ea8ce3afd) which takes a QDomNode from the sld, I suspect that there some issue in updating the layer sld style using python( may be some contexts eg. rendering contexts are not available through python bindings, not sure yet about this though), I'm still investigating the issue, on other hand the QgsMapLayer.loadSldStyle works fine when using it and the styles are loaded properly.

2021-02-23 11:40 UTC, ricardogsilva commented
@Samweli 

I've been doing some research and I could load the SLD onto the QGIS layer

Here is a sample code I prepared that is runnable in the QGIS Python console

```python
import json
from pathlib import Path
from urllib.parse import urlparse

import requests

import qgis.core
from qgis.PyQt import QtXml

base_url = "https://master.demo.geonode.org"

layer_name = "Traffic_Lights"
layer_response = requests.get(
    f"{base_url}/api/v2/layers/",
    params={"filter{name}": layer_name}
)
reported_sld_url = layer_response.json()["layers"][0]["default_style"]["sld_url"]
parsed_url = urlparse(reported_sld_url)
new_url = f"{base_url}{parsed_url.path}"
sld_response = requests.get(new_url)
sld_doc = QtXml.QDomDocument()

# `True` as the second parameter here enables XML namespace 
# processing, which is crucial for QGIS to be able to parse the SLD
sld_loaded = sld_doc.setContent(sld_response.content, True)

if not sld_loaded[0]:
    raise IOError("Could not load SLD response into a QDomDocument")

sld_root = sld_doc.documentElement()
sld_named_layer = sld_root.firstChildElement("NamedLayer")

# now to load QGIS layer with our SLD

qgis_layer = qgis.core.QgsVectorLayer(
    f"/datadisk/data/test_data/{layer_name}.zip",
    layer_name,
    "ogr"
)
if not qgis_layer.isValid():
    raise IOError("Could not load QGIS layer")
    
error_message = ""
style_loaded = qgis_layer.readSld(sld_named_layer, error_message)
if not style_loaded:
    print("Unable to load SLD onto the layer")

qgis.core.QgsProject.instance().addMapLayer(qgis_layer)
```

Please study this snippet and adapt your PR to make use of a similar technique. Then let me know so that I can review

2021-02-23 12:10 UTC, Samweli commented
> Please study this snippet and adapt your PR to make use of a similar technique. Then let me know so that I can review

sure thanks

2021-02-23 22:54 UTC, ricardogsilva approved these changes
I added a commit that refactors your proposed implementation in order to make loading the SLD style a responsability of the API Client class. The spirit of the code is the same, I just moved some stuff back to the API client

2021-02-23 23:04 UTC, merged