Support for ordering when searching resources
kartoza/qgis_geonode pull request #116
Opened 2021-02-24 06:10 UTC by Samweli

Fixes https://github.com/kartoza/qgis_geonode/issues/63

Adds ordering parameter in the GeonodeClient backend and new UI items to support ordering when searching for resources.
Currently the implementation works on only the "name" field, when using others fields including "title" and "abstract" the search results into a "ProtocolInvalidError".

2021-02-24 10:45 UTC, ricardogsilva commented
@Samweli 

Before I review this:

- Update this branch in order to have the latest stuff from `master`
- Remove the `draft` status
- Add support also for the `csw` API client class. Consult the [CSW version 2.0.2 standard](https://portal.ogc.org/files/?artifact_id=20555), namely section 10.8.2 (GetRecords Operation, KVP encoding), table 65. Briefly, you will need to add the `SortBy` parameter with a suitable value

2021-02-25 13:15 UTC, ricardogsilva requested changes
Still needs work.

On my local tests I could not get this to work at all. I'm using `master.demo.geonode.org` as my test server with both `APIV2` and `CSW` API version types. These are my results:

### APIV2

Order by `Name` does not work:

```python
AttributeError: 'NoneType' object has no attribute 'get' 
Traceback (most recent call last):
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/gui/geonode_source_select_provider.py", line 259, in handle_layer_list
    self.populate_scroll_area(layer_list)
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/gui/geonode_source_select_provider.py", line 283, in populate_scroll_area
    search_result_widget = SearchResultWidget(
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/gui/search_result_widget.py", line 57, in __init__
    url = geonode_resource.service_urls.get(service_type)
AttributeError: 'NoneType' object has no attribute 'get'
```

Order by `Title` does not work either:

```
Problem in searching, network error 302 - ProtocolInvalidOperationError
```


### CSW 

Order by `Name` does not work:


```python
AttributeError: 'NoneType' object has no attribute 'attrib' 
Traceback (most recent call last):
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/base.py", line 220, in response_fetched
    handler(payload)
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/csw.py", line 113, in handle_layer_list
    total = int(search_results.attrib["numberOfRecordsMatched"])
AttributeError: 'NoneType' object has no attribute 'attrib'
```

Order by `Title` does not work either:

```python
AttributeError: 'NoneType' object has no attribute 'attrib' 
Traceback (most recent call last):
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/base.py", line 220, in response_fetched
    handler(payload)
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/csw.py", line 113, in handle_layer_list
    total = int(search_results.attrib["numberOfRecordsMatched"])
AttributeError: 'NoneType' object has no attribute 'attrib'
```

Furthermore, when there is an error the interface becomes unusable because the buttons do not return to their original state.


In addition, I've left some inline comments about these:

- GUI layout is ugly
- You are leaking the name of the parameters used by the API version(s) to perform the ordering outside of the API client class(es)

2021-02-25 13:15 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/apiv2.py
> +                ordering_field = "-{}".format(ordering_field)
You are again leaking the name of the GeoNode API fields outside of the API client class.

The caller of this code should not need to know the exact name of the field that is sent to the API. The name of the sort field can be different across API versions.

On top of that you are also binding the string shown on the GUI to the parameter sent to the API, which is also undesirable, as we may want to name things differently in the UI (for example, let's say I want the UI to show `Title` but instead I will order by the `name` field when I call the API).

the `ordering_field` param shall have a known type instead of a simple `str`. Make an enum like this:

```
class OrderingType(enum.Enum):
    TITLE = "title"
```

and use that as the type of the `ordering_field`. Then inside the function you can map that value onto whatever the GeoNode API expects to be used for the actual request

2021-02-25 13:15 UTC, ricardogsilva commented on src/qgis_geonode/apiclient/csw.py
> +            query.addQueryItem("sortby", ordering_value)
This does not work.

As mentioned above, the `ordering_field` to be used is not what is passed to the function and is not what is shown on the GUI.

CSW endpoints expect something like:

```
sortby=apiso:Title
```

Please take note of the previous comment and implement a more encapsulated way of performing the ordering whereby the name of the actual parameter that is sent to the API is not controlled by whoever is calling these functions.

2021-03-03 01:07 UTC, ricardogsilva commented
@Samweli any update on this PR?

2021-03-03 11:18 UTC, Samweli commented
> @Samweli any update on this PR?

@ricardogsilva I have just update the PR with latest changes.

2021-03-03 14:17 UTC, ricardogsilva commented
@Samweli 

Please resolve all conflicts before I do a review

2021-03-04 17:30 UTC, ricardogsilva approved these changes
Nice work to fix the requested stuff.

There were some things that were still not quite done yet, so I went ahead and worked on them in order to avoid keeping us locked to this issue.

Some of the stuff I changed:

- Tweak the GUI further
- Better abstract name of the order field(s) from the API client and GUI
- Make ordering mandatory
- Be consistent with the representation shown to the user. Use `name` as the name of the ordering field but then either use `name` or `title`, according with the concrete API client class. Also, adjust the result to show the same thing that was used in the ordering (i.e. if we ordered by `title` then the search results show the item's title and if we ordered by `name`, then the search results show the item's name)

2021-03-04 17:31 UTC, merged