Add progress message when testing connection
kartoza/qgis_geonode pull request #150
Opened 2021-03-31 12:14 UTC by Samweli

Fixes https://github.com/kartoza/qgis_geonode/issues/70

Adds progress bar in the message bar, using the same approach used in the main widget to add the progress message when searching or loading resources.

2021-04-07 11:32 UTC, ricardogsilva requested changes
Please modify the message bar so that it does not cause the UI to jump around when it is enabled/disabled.

Check the code of the main plugin UI to see how it is being done there

2021-04-08 13:51 UTC, Samweli commented
> Check the code of the main plugin UI to see how it is being done there

@ricardogsilva  I tried using the approach on the main UI but couldn't fix the issue, I have updated the connection dialog to use Grid Layout instead in order to fix the issue.

2021-04-08 14:25 UTC, Samweli commented
noticed that the progress bar now blocks the service name input, working on resolving this...

2021-04-09 12:54 UTC, ricardogsilva requested changes
I still see the UI elements moving around when the message bar shows/hides.

We want a similar effect as the one we have on the main UI:

- We don't want users to change the configuration while the test is running, so when the `test` button is clicked, all input widgets should be temporarily disabled for the duration of the test request and then re-enabled after the test is done
- During the test, the message bar shows up on top of whatever widgets are there
- it does not matter that the message bar covers up other widgets, as these shall be disabled while the test is running.

2021-04-12 10:22 UTC, ricardogsilva requested changes
Looks good, I'm just wondering about that RuntimeError mentioned in the comment inline. When we clear that up I'll be OK to merge.

2021-04-12 10:22 UTC, ricardogsilva commented on src/qgis_geonode/gui/connection_dialog.py
> +            try:
`setEnabled()` is a method of `QWidget` so I guess this should never be throwing RuntimeError. Did you see this error being raised while implementing these changes? If so, which widget raised it? Otherwise, please remove the try..except block

2021-04-12 10:22 UTC, ricardogsilva commented on src/qgis_geonode/gui/connection_dialog.py
> +                pass
See the comment above about removing this try..except block

2021-04-12 15:52 UTC, ricardogsilva commented on src/qgis_geonode/gui/connection_dialog.py
> +            try:
Oh, I see. In that case, lets merge this then :+1:

2021-04-12 15:52 UTC, merged