Editing user guide
kartoza/qgis_geonode pull request #160
Opened 2021-04-21 11:51 UTC by Samweli

Fixes https://github.com/kartoza/qgis_geonode/issues/153

Adds sections in the user guide as outlined in the  https://github.com/kartoza/qgis_geonode/issues/153 issue.

2021-04-22 17:28 UTC, ricardogsilva requested changes
Not quite ready yet, but it is a good start!

Please work on the suggested changes and then I will do another review.

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +## Introduction
No need for an `Introduction` sub section, just put this paragraph below the main header

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +integration which has been implemented in the QGIS core.
This seems a bit thick to me. I am not getting much value from these sentences. When writing documentation, please remember that _less is more_, as the user can quickly become bored. Personally I would just remove these. alternatively, please make it more succinct.

Also, I don't think we need to compare this plugin with the (soon to be legacy) support that is in QGIS core. That is something we will write about in the upcoming QEP.

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +   ![GeoNode Plugin Provider](https://github.com/kartoza/qgis_geonode/raw/main/docs/images/user_guide/data_source_manager-qgis_geonode.png)
Don't add images like this. It makes it impossible to test them locally without publishing the changes. Use a relative path to the image, in a similar way as is done on the `index.md` page.

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +1. Open the main plugin provider widget by opening the data source manager dialog and click
This language is too technical. End users do not know what the `main plugin provider widget` is. You should write something that is easier to grasp for an outsider. For example:

"Open the QGIS Data source manager window (Ctrl+L) and navigate to the _GeoNode Plugin Provider section_..."

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +choose the authentication configurations for the instance using the QGIS authentication configuration selector widget available on the connection dialog.
We need more detail on this authentication part.

Consider that end users might not know how to configure an OAuth2 authentication on QGIS.

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +5. There is button with a label "Test Connection" can be used to test if the GeoNode connection is valid. If the
Please take care about using correct spelling and grammar.

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +
Please include a screenshot with an example configuration for accessing the geonode demo server

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
>  ### GeoNode API V2
These sections are also in scope for this task. Please explain briefly what is the difference between these two versions and how one would go about creating a connection to connect to each one both with and without authentication

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +  Make sure the intended GeoNode instance connection is selected from the connections list inside the Connection
Be sure to test stuff locally by using the mkdocs test server. You can activate it with:

```
poetry run mkdocs serve
```

Otherwise you may miss some text formatting issues, as is the case here. Make sure text is indented properly in order for it to appear on the intended bulleted lists

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +  group box, then click the "Search Geonode" button, a progress bar will be shown with a message "Searching...",
Mentioning the progress bar is not necessary here. Keep it brief in order to not bore the user that is reading this documentation.

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +  ![search results](https://github.com/kartoza/qgis_geonode/raw/main/docs/images/user_guide/example_search_results.png)
Same comment as above, do not use full URLs when including images

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +    The support for `spatial extent` is not yet implemented.
We need to mention that the availability of these search filters depends on the API version being used and that not all of them are currently supported

2021-04-22 17:28 UTC, ricardogsilva commented on docs/user-guide.md
> +  left of the "Sort by" combo box.
Be consistent with the subject of your sentences. Here you write:

> Users can change the order...

But above you were using a more direct speech:

> Make sure the intended GeoNode instance connection is selected from the connections list inside the Connection

2021-04-23 10:05 UTC, Samweli commented on docs/user-guide.md
> +  Make sure the intended GeoNode instance connection is selected from the connections list inside the Connection
Right will do, I was using pycharm markdown viewer and it didn't have the issue.

2021-04-29 17:27 UTC, ricardogsilva requested changes
Writing docs is harder than it seems, eh :smile:

Please work on it a bit more.

Generally I would say that you should try to 

- Take care to use correct language constructs
- Avoid making too long sentences
- Cut down on words that don't add much to the overal text. We want to keep it brief and direct

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +3. Enter the GeoNode instance details "Name" and "URL", if the instance supports authentication, you can
Please make it explicit that for URL the user should use the main GeoNode URL.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +     ![Adding authentication configuration](images/user_guide/adding_authentication.png)
Image too tall. Please make it smaller

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    Select the type that you want, and add all the required credentials then click save the
Most likely the users will not know what authentication they want. Please reword this. We need to make it very clear how to authenticate:

- For API v2 the only option we recomend is OAuth2 with the Authorization Code flow. Do not recomend the Resource Owner flow, as I've had some trouble using it (trouble seems to be related with QGIS caching credentials somewhere)
- For the legacy API users need to use both OAuth2 with Authorization Code flow and also provide their username and password on the additional UI controls that are shown.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +5. Set the search results page size inside the page size input. By default, the size is 10,
This sentence is confusing, please reword it

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +6. Test the GeoNode instance connection by using a button with a label "Test Connection", click the button and if
This is boring content that does not add much. A simple 'Press the Test Connection' button to verify if the connection works' is sufficient.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +   Connection configurations using GeoNode demo instance
Please use full sentences. In this case, I guess it would be something like 'The picture below shows how you can configure anonymous access to the main GeoNode demo server'

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +   ![GeoNode demo connection](images/user_guide/master_demo.png)
Image too big, please make it smaller

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
>  ### GeoNode API V2
These two sub-sections should be integrated into the text above, when speaking about authentication.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +- Searching layers
Don't use bullet points here. I had used them initially just to define a skeleton for this document. They are not needed anymore and even make the text uglier.

Alternatively, use sub-sections

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    Make sure the intended GeoNode instance connection is selected from the connections list inside the Connection
This sentence is very long. Please break it down.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    ![search results](images/user_guide/example_search_results.png)
This image does not need to show the advanced group box as being expanded. You are speaking about the simplest case where the user just presses the search button and gets back results.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    populated in a scroll area below the search buttons.
Please mention the pagination of search results and how users can navigate to the next/previous page

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    Each of the API version has a set of supported filters,
Instead of this, please use a bulleted list where each search filter is described. After having described all search filters you can mention that their availability depends on the API being used

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    when it is checked.
There needs to be a new line here, otherwise the rendering gets messed up. Anyway, if you move to a subsection layout instead of these bulleted lists the problem will be gone

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    QGIS OGC providers (WMS for maps, WFS for vector and WCS for raster resources), in order to load the layer in QGIS
Please reword this, as the sentence is confusing. Additionally, please avoid using parenthesis - If you feel the need to put something in between parenthesis then that is probably not important enough to be on the text. Alternatively, make a proper sentence to describe the thing that would be parenthesized.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    For the vector based resources WFS button be available, raster resources will contain the WCS button and WMS always be
Reword this, as the sentence is confusing and mixes too many things.

2021-04-29 17:27 UTC, ricardogsilva commented on docs/user-guide.md
> +    When loading the layer inside QGIS, the provider also load the available metadata from GeoNode into QGIS
Reword this and also add a screenshot

2021-05-11 11:32 UTC, ricardogsilva approved these changes
I commend your effort!

However I think it is still somewhat crude and not ready for public consumption. Nonetheless, I don't want to beat you around with this too much, in order to avoid trauma :laughing: 

LGTM and later we can revisit this.

2021-05-11 11:42 UTC, merged