Added a custom dialog in the QGIS data source manager
kartoza/qgis_geonode pull request #19
Opened 2021-01-05 13:15 UTC by Samweli

Work for https://github.com/kartoza/qgis_geonode/issues/13

2021-01-05 16:33 UTC, ricardogsilva commented on src/qgis_geonode/gui/geonode_provider.py
> +class GeonodeProvider(QgsSourceSelectProvider):
how about you name this `GeonodeSourceSelectProvider` instead? Seems more inline with QGIS naming

2021-01-05 16:41 UTC, ricardogsilva commented on src/qgis_geonode/qgisgeonode/main.py
> +
From my local tests this only seems to add/remove the provider to the QGIS data source manager dialog after restarting QGIS.

I mean that when the plugin is installed (or manually enabled/disabled in the QGIS plugin manager) there is no change to the QGIS data source manager dialog. Only after restarting QGIS do I see a change.

Perhaps there is a signal that needs to be emitted? Looking at the [QGIS API docs](https://qgis.org/api/classQgsSourceSelectProviderRegistry.html), it seems it is not possible to dynamically reload the list of providers. Did you do any research on this?

What are our options here?

2021-01-06 06:14 UTC, Samweli commented
> Also, please don't just add stuff remove also unused code. I am thinking especially of the `main.py` module, that seems to be accumulating a lot of unused stuff related to the dock widget, and also the `Qgis_GeoNode_dockwidget.py` file too, which seems to be irrelevant now.

Yes, can I do this on a separate PR?

2021-01-06 07:49 UTC, Samweli commented on src/qgis_geonode/qgisgeonode/main.py
> +
> From my local tests this only seems to add/remove the provider to the QGIS data source manager dialog after restarting QGIS

@ricardogsilva I confirm this

> Did you do any research on this?

No I didn't 

> What are our options here?

I'm taking a look at the QGIS API, will let you know once I find out what we need to do.

2021-01-06 08:15 UTC, Samweli commented on src/qgis_geonode/qgisgeonode/main.py
> +
@ricardogsilva I have looked at the implementation details of "addProvider()" and "removeProvider()" seems there is no code that work on updating dynamically the provider list on the data source manager dialog other than updating (by adding or removing) the provider list.

We could make effort to add signal to the https://qgis.org/api/classQgsSourceSelectProviderRegistry.html as you have suggested above and connect to it in https://qgis.org/api/classQgsDataSourceManagerDialog.html in order to update the dialog providers list.

2021-01-06 10:19 UTC, ricardogsilva requested changes
Almost ready, just a couple of small changes left:

- Please clean up the code in `main.py` and remove unused gui files - I prefer having that in this PR, since it relates to the same thing
- Please remove the `src/__init__.py` file as it should not be needed (I'm guessing probably your IDE added that by default?)

As for the load/reload of the sourceselect provider, since this is something that needs changing in QGIS core, lets leave it like this for now. We will contribute the change to QGIS core first and then eventually adjust our code here to  make use of it.

2021-01-07 15:08 UTC, merged