Adding Layer search functionality
kartoza/qgis_geonode pull request #59
Opened 2021-01-15 16:32 UTC by Samweli

This is a draft PR which aims to fix https://github.com/kartoza/qgis_geonode/issues/30. It contains work from 
https://github.com/kartoza/qgis_geonode/pull/54
At the moment this work is only capable of fetching the first page of layers list from the GeoNode API and display the layers titles on the list widget.

Items that have not been covered yet.
- [ ]  "Next" and "Previous" button functionality
- [ ]  Showing layer abstract on the displayed list.

2021-01-19 15:56 UTC, ricardogsilva requested changes
It is a good start :smile_cat: but there's still stuff to adjust. I think we will do one or two more review cycles of this.

As a preamble, please remember to update the PR description when you set it to not be a draft anymore, as the content of the description is no longer valid.

- [x] No feedback is given for invalid GeoNode connections - make use of the `GeonodeClient.error_received` signal and show the user some feedback when a request did not work OK
- [ ] Please do not change the mouse cursor when a request is loading, as that sets an expectation that the GUI is frozen when in reality it isn't - use some other visual indicator (e.g. a progress bar) instead
- [x] Pagination does not work OK for the first page
- [x] There is a lot of wasted space below the search results area - adjust search results widget to take up all possible space
- [x] Re enable the `Search Items` group box (but not the individual widgets inside it) so that we may test how the search results area expands when this area is collapsed/expanded
- [x] Be more consistent with naming: Qt and QGIS want to name everything with `camelCase`. But Python's convention is to use `snake_case` instead, so please use that (e.g. instead of defining a `currentPage` variable, name it `current_page`)
- [ ] For showing the search results, instead of a `QTreeWidget` and multiple `QTreeWidgetItem`s, use a `QScrollArea` combined with the custom widget you had designed earlier (`ui/qgis_geonode_searched_resource.ui`, which by te way you could rename to something terser, like `search_result_widget.ui`). This shall give us more flexibility in presenting the search results (e.g. for showing a thumbnail of each result, etc). Check this nice tutorial on how to use scroll area if needed: https://www.learnpyqt.com/tutorials/qscrollarea/
- [ ] Clear any search results when the user selects a different GeoNode connection from the dropdown at the top
- [ ] Instantiate geonode client by using `GeonodeClient.from_connection_settings`, as that will make sure to include all relevant parameters in the initialization (e.g. you are currently not passing the auth_config)

2021-01-21 08:34 UTC, Samweli commented
@ricardogsilva I have updated the PR with the latest changes.

> * Please do not change the mouse cursor when a request is loading, as that sets an expectation that the GUI is frozen when in reality it isn't - use some other visual indicator (e.g. a progress bar) instead

I have added a progress message bar, I couldn't get progress bar to work within the given time.



> * For showing the search results, instead of a `QTreeWidget` and multiple `QTreeWidgetItem`s, use a `QScrollArea` combined with the custom widget you had designed earlier (`ui/qgis_geonode_searched_resource.ui`, which by te way you could rename to something terser, like `search_result_widget.ui`)

I have used the `search_result_widget` and QScrollArea, but I'm having some issues in showing the widgets content inside the scroll area, may be there is some setting I'm missing in using the QScrollArea.

2021-01-21 10:26 UTC, ricardogsilva requested changes
Some small changes that are blocking me from doing a proper review. Please fix ASAP

2021-01-21 10:26 UTC, ricardogsilva commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +from qgis_geonode.gui.search_result_widget import SearchResultWidget
This does not work due to recent changes introduced by #62 - did you test it?

2021-01-21 10:26 UTC, ricardogsilva commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +from qgis_geonode.gui.search_result_widget import SearchResultWidget
Please organize your imports so that they go like this:

1. standard library
2. third-party dependencies
3. own code

Also, please use relative imports instead of absolute ones (e.g. prefer using `from .. import api_client` instead of `from qgis_geonode import api_client`)

2021-01-21 10:29 UTC, ricardogsilva commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +from qgis_geonode.gui.search_result_widget import SearchResultWidget
Also, whithin their logical group, please sort imports alphabetically

2021-01-21 10:37 UTC, Samweli commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +from qgis_geonode.gui.search_result_widget import SearchResultWidget
the apiclient package remained in my local repo, so it was still working.

2021-01-21 13:43 UTC, ricardogsilva requested changes
After my recent push using the custom search result widget should be working.

Please fix the comments marked with `TODO` and `FIXME` on the files related to this PR and verify if things are working and then re-request a review.

2021-01-21 18:57 UTC, ricardogsilva commented
@Samweli as stated offline, please fix #71 and #72 too as a part of this PR

2021-01-22 10:28 UTC, ricardogsilva requested changes
Please fix the error descriptions, relevant for #72

2021-01-22 10:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +        )
The error that is sent to this function is a [QNetworkReply.NetworkError](https://doc.qt.io/qt-5/qnetworkreply.html#NetworkError-enum), not an HTTP status code. You are mixing these up here, which causes confusion. For example:

![Screenshot from 2021-01-22 10-04-53](https://user-images.githubusercontent.com/732010/105477626-0398da00-5c9a-11eb-9868-92327217c23d.png)

Now I don't see the error code anymore, but I get a message that would indicate success because you are showing the text for HTTP 203 (which is success) as if it were the description of `QNetworkReply.NetworkError.ContentNotFoundError`, which has the code `203`

Please use the name of the Qt error. See here for a possible implementation:

https://stackoverflow.com/a/39677321

2021-01-22 10:28 UTC, ricardogsilva commented on src/qgis_geonode/utils.py
> +    return errors[code]
as mentioned in the comment above, these should not be here, as we are not dealing with HTTP status codes directly. Please remove.

2021-01-22 10:37 UTC, Samweli commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +        )
ooh I completely miscalculated  that!

2021-01-22 12:34 UTC, ricardogsilva approved these changes
All seems to be working. Thanks for the effort!

2021-01-22 12:34 UTC, merged