Load GeoNode layers into QGIS
kartoza/qgis_geonode pull request #74
Opened 2021-01-26 12:58 UTC by Samweli

Fixes https://github.com/kartoza/qgis_geonode/issues/56

This PR adds functionality for loading the GeoNode layer search results as QGIS layers.
 It would have been nice if we could determine from API layer response if the search result layers types so as to know whether to enable or disable the "WFS"/"WCS" buttons, at the moment there is no way to know about the layer type.

![loading_layers](https://user-images.githubusercontent.com/2663775/105847771-1a6b6380-5fef-11eb-94b2-fcf8dd50c32c.gif)

2021-01-26 14:12 UTC, ricardogsilva requested changes
It is satisfying to see the layers beginning to show up on QGIS :smile: 

However, there are some things that need adjusting. Please work on them and then we'll do another review

2021-01-26 14:12 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            return
This should show an error to the user - As a general rule, don't swallow errors silently

2021-01-26 14:12 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            log("Problem loading the layer into QGIS")
Let the user know that there was an error by showing something on our message bar

2021-01-26 14:12 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +        return uri
As mentioned above, this method belongs in `api_client.BriefGeonodeResource` instead. We have all the necessary information to build the URIs there.

The response-parsing classes in `api_client` are going to be the main interface for the rest of the plugin to deal with. This way we will likely be able to add support for other GeoNode versions in the future without having to rewrite much of the code.

Also, don't forget to include the auth config in the final URLs - otherwise we are only going to be accessing public layers

As for not knowing the type of a layer, there is `BriefGeonodeResource.resource_type` which should contain that information.

2021-01-27 10:36 UTC, ricardogsilva requested changes
Almost done, just do some light refactoring (as requested) to improve testability

2021-01-27 10:36 UTC, ricardogsilva commented on src/qgis_geonode/api_client.py
> +
For improving the testability of this code, please:

- Implement the code as standalone function(s) since you are not using any of the class or instance properties. Having this as a static class method brings little (if any) added value.
- Refactor this into three distinct functions

Follow a similar approach as the one taken for other small functions that serve this class, like `_get_temporal_extent`, `_get_spatial_extent`, `_get_resource_type`, etc.

2021-01-27 10:36 UTC, ricardogsilva commented on src/qgis_geonode/api_client.py
> +            urls[key] = cls.construct_ogc_uri(base_url, key, payload)
There is a `resource_type` property on `GeoNodeBriefResource` that you can use to find it if this is a map, raster or vector. Use that to only build the relevant URLs - i.e. there is no point in having a WCS URL if the layer is a vector.

2021-01-27 10:36 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            log("Problem loading the layer into QGIS")
Please refactor this:

- [ ] Rename `wms_button_clicked` to `load_raster_resource` (and similar for `wfs_button_clicked`), since that describes what the function does (rather than naming the function according to what event triggered it, which adds little value)
- [ ] Please don't generalize layer loading in the `load_ogc_layer` method. You can load each layer type in its own `load_{resource}_resource` method, which is already there too. When a function's main logic is being handled in an `if..else` block that is usually a good indication that it should be split into smaller-scoped functions (this is especially evident in Python, because the indentation levels start piling up).
- [ ] There is little gain in having two separate error handling parts of the code here - i.e. one that checks for a valid URI before trying to load the layer and then another that checks if the layer loading worked. Just try to load whatever URI is there and then check for `layer.isValid` after having loaded the layer, as you are doing already.

2021-01-27 22:45 UTC, ricardogsilva commented
@Samweli 

I wasn't able to test if the auth config is being properly handled when loading private layers because:

- I don't have a proper local GeoNode environment set up (lost it after switching computer recently)
- I don't have admin access to the official GeoNode demo server in order to retrieve the relevant OAuth2 parameters that would allow me to use authentication

Were you able to verify that these work OK?

I am going to accept this PR, but we need to confirm that the authentication works OK. Hopefully next week I will be able to set up my local GeoNode env again.

2021-01-27 22:45 UTC, ricardogsilva approved these changes
Looking good now, thanks for your hard work!

2021-01-27 22:46 UTC, merged

2021-01-28 07:28 UTC, Samweli commented
> Were you able to verify that these work OK?

I also wasn't able to verify, I will be confirming the authentication today, then I ll get back to you.

2021-01-28 07:28 UTC, Samweli commented
> Looking good now, thanks for your hard work!

thanks @ricardogsilva