Adding metadata into the QGIS layer
kartoza/qgis_geonode pull request #78
Opened 2021-01-29 14:17 UTC by Samweli

This PR has work for fixing https://github.com/kartoza/qgis_geonode/issues/57

Right now only few of the GeoNode metadata fields are loaded into the layer, I'm continuing adding more fields and will update the PR when finished.

2021-01-29 23:57 UTC, ricardogsilva requested changes
Please work on the requested changes before we can merge this.

2021-01-29 23:57 UTC, ricardogsilva commented on src/qgis_geonode/api_client.py
> +    metadata_author: typing.Dict[str, str]
I think these additional fields should be added to the `GeonodeResource` class instead of `BriefGeonodeResource`. The GeoNode API is till evolving and it is very likely that what is returned by the `/layers` endpoint will be a reduced representation of each layer. So we should keep the properties of `BriefGeonodeResource` to a minimum.

The strategy shall be to, once we know that we are going to load a specific layer, we make a new call to the API, this time to the `/layers/{layerId}/` endpoint and we create a new `GeonodeResource` instance with a more comprehensive set of properties, which we then use to populate the layer's metadata info on QGIS.

2021-01-29 23:57 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            self.populate_metadata(layer)
As mentioned above, we need to do a request to the layer detail endpoint and then use that response to get the full set of metadata.

2021-01-29 23:57 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +        )
I am not seeing the layer's UUID being shown here. This property is crucial for use, since we will need to use it later on, to determine if a layer came from GeoNode in the first place.

Be sure to add this property.

2021-01-30 14:15 UTC, Samweli commented on src/qgis_geonode/gui/search_result_widget.py
> +        )
@ricardogsilva should I add another uuid field in the GeonodeResource to reflect the uuid from the GeoNode API?

2021-01-31 22:38 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +        )
> should I add another uuid field in the GeonodeResource to reflect the uuid from the GeoNode API?

I don't understand this question.

A GeoNode resource has the `uuid` field. We need to make this visible in the QGIS layer metadata. It shall correspond to the  layer's `Identifier` metadata property

2021-01-31 23:28 UTC, ricardogsilva requested changes
Still some ways to go.

Please work on the requested changes

2021-01-31 23:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +        client.get_layer_detail(pk)
The act of loading a layer needs to be refactored, as it is becoming a bit convoluted.

- [ ] Each of the `load_map_resource()`, `load_vector_layer()`, `load_raster_layer()` methods should not be re-enabling the corresponding buttons because we still need to make an async request to the GeoNode API. These buttons should only be re-enabled after we get a response from the API and are ready to load the layer;
- [ ] The `load_layer()` method just does error checking and then calls another `get_layer()` method. This seems needlessly complex. Stick the logic that is in `get_layer()` directly inside `load_layer()` . Also, please put the error checking branch of the `if.. else` below the branch that does stuff.
- [ ] The `get_layer()` method should not need to retrieve the connection settings again. This should be passed to the instance upon initialization. The reason for this is that when you retrieve the connection settings by calling `connections_manager.get_current_connection()` you cannot be sure that you are getting back what the user has currently selected, as `get_current_connection()` returns what is saved in QgsSettings, not what is selected on the combo box.
- [ ] `get_layer` does not need to receive the `pk` argument because you already have the `self.geonode_resource` property on the class instance. Retrieve the `pk` from there

2021-01-31 23:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +    def populate_metadata(self, layer, geonode_resource):
This function does more than populating metadata, it also loads the layer onto QGIS map canvas, which is really the most important part of the function. As such, this is not an appropriate name for the function. I suggest using `show_layer()`

2021-01-31 23:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            metadata.setLicenses([geonode_resource.license['identifier']]
license is defined above in `GeonodeResource` as being a string. Here it is treated like a dictionary instead, which means it is not being properly parsed from its original JSON payload. Please fix this. Parse the license into a string directly in `GeonodeResource` instantiation.

I am working on adding support for older GeoNode versions where I will be retrieving metadata from XML responses. As such we need to be careful not to rely on the JSON payload that is returned from the V2 API and properly parse the payload into simple data types instead

2021-01-31 23:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +        metadata.setCrs(geonode_resource.crs)
This does not seem to be working. On my local tests I always see `CRS: not set`. However, if I go to the layer's `Information` section I can see the CRS being reported there

![qgis-geonode-crs-not-set](https://user-images.githubusercontent.com/732010/106401179-a5e35b00-641a-11eb-8ac5-52ed70dc1c19.png)

2021-01-31 23:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            links.append(link)
This shows a relative URI instead of a URL. Please fix it in `BriefGeonodeResource`

2021-01-31 23:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +        QgsProject.instance().addMapLayer(layer)
As mentioned above, now, after loading the layer, it is a good time to re-enable the layer-loading buttons on the UI

2021-01-31 23:28 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +        metadata = layer.metadata()
As mentioned previously, please be sure to show the geonode resource's `uuid` in the layer's `Identifier` metadata field

2021-02-01 06:58 UTC, Samweli commented on src/qgis_geonode/gui/search_result_widget.py
> +        )
> A GeoNode resource has the `uuid` field

This uuid field is generated in the plugin, but the layer API response also has an uuid field, shouldn't we use the one from the API?

2021-02-02 08:50 UTC, ricardogsilva approved these changes
Nice work, all my previous comments have been addressed, and I see you are also fixing #76 too (I updated the PR dewscription with a link to it, in order to have github autolink the issue with the PR).

I am OK for merging now :tada: 

With regard to metadata support we will need to revisit this later on, at least for the `Type` property (which seems to be the only one causing the automated QGIS validation to fail, because it is empty) shall always be `dataset` - I'll open an additional issue for this.

We are also able to add quite a few additional metadata fields if we use a resource's CSW endpoint. However, at this point I think what we have is a good start.

2021-02-02 08:51 UTC, merged

2021-02-02 10:59 UTC, Samweli commented
Thanks for the merge @ricardogsilva :+1: