Adding search filtering in the API client
kartoza/qgis_geonode pull request #85
Opened 2021-02-04 14:16 UTC by Samweli

Fixes https://github.com/kartoza/qgis_geonode/issues/29

Adds support in the API client for using search filters on the GeoNode V2 API. The added tests are only covering the equality operation for filtering.

The logic for creating filtering query strings is left for API client users(GUI).

2021-02-05 10:42 UTC, ricardogsilva requested changes
Not really ready for merging yet, please work on the comments

2021-02-05 10:42 UTC, ricardogsilva commented on src/qgis_geonode/api_client.py
> +
This code leaks details from GeoNode API outside of the API client class, which is not desirable.
The callers of this method shall not need to know the names of the search filters, this information must be encapsulated in the API client class - otherwise it will be harder to implement support for other GeoNode versions.

Please add function parameters for each search filter instead. Example:

```python
def get_lyaers(self, title_pattern: typing.Optional[str] = None):
    # existing code
    if title_pattern is not None:
        query.addQueryItem("title", title_pattern)
    # existing code
```

This means that the API client class explicitly knows which search filters it supports. Be sure to add support for the all search parameters shown on the original issue description

2021-02-05 10:42 UTC, ricardogsilva commented on src/qgis_geonode/api_client.py
> +
As mentioned above, this approach is not suitable. Use a similar approach as the one mentioned in the previous comment

2021-02-05 10:42 UTC, ricardogsilva commented on test/_mock_geonode.py
> +            "layers",
Tests should be dumb - Please make test endpoints be dumber, otherwise we may need to write tests for verifying the tests :upside_down_face: 

Just have the `_mock_layer_list` return the expected response when the request URL (with the query string) matches an expected pattern.

2021-02-05 11:10 UTC, Samweli commented on test/_mock_geonode.py
> +            "layers",
> Tests should be dumb - Please make test endpoints be dumber, otherwise we may need to write tests for verifying the tests

Sure, :)

2021-02-08 13:54 UTC, ricardogsilva approved these changes
I did a refactor of your proposed implementation in order to make it a bit clearer.

I think it is good to merge now.

2021-02-08 13:57 UTC, merged