Support for search filtering in the GUI
kartoza/qgis_geonode pull request #87
Opened 2021-02-09 23:16 UTC by Samweli

Fixes https://github.com/kartoza/qgis_geonode/issues/80

Adds search filtering via GUI, now it searches using all the field items except start, end and spatial extent items.
The current search filtering doesn't support filtering with more than one field, The free text is treated as a title when filtering, abstract will be included once a better way of filtering two different fields has been
devised.

The search filter items UI is updated to included checkboxes that will allow user to later have options about which items they want to include in filtering resources.

This PR also adds fetching of all keywords in the GeoNode instance using endpoint '/h_keywords_api'.

Screenshot
![search_filtering](https://user-images.githubusercontent.com/2663775/107441115-bcd62b80-6b45-11eb-9c4b-bb2e7ef2978d.gif)

2021-02-10 13:13 UTC, ricardogsilva requested changes
There are quite a few things to work on this time around. In addition to the inlined comments, please also consider these:

1. Loading the available keywords is a slow operation and slows down the QGIS GUI. 

   This is noticeable when opening up the QGIS connections manager dialogue the first time - on my system it is taking more than three seconds to open this dialogue after having started QGIS. 

   This is highly undesirable. As an alternative, please implement loading existing keywords on-demand, when/if the user needs them. Add an additional `QToolButton` to the right of the `keywords` combobox that the user can press to have the keywords be loaded when needed.


2. Please add an additional `abstract` line edit in order to enable searching for text in the abstract. 

   As mentioned in the original issue description, there is currently no way to do searching across multiple text properties on the GeoNode API. This does not seem like a trivial thing to implement so I guess it is likely that it will not be added to the API soon. As such we shall not wait around, let's provide a way to allow searching the abstract. This means adding an extra line edit in the GUI and also adding additional search parameters in our client class


3. I see you modified the original interface a bit, which in principle is not a bad thing to do. However, in this case I'm sorry to say I do not agree with most of the changes. My reasoning being that they force the user to do a lot of extra clicking, which IMO is undesirable:

   - I don't agree with making the `search items` collapsible group box checkable. We should rather design the search filters in such a way as to make it possible to use search without having selected anything in any filter.


   - I also do not agree with having each search filter being gated by a checkbox. This causes too many clicks, as the user must:

     1. expand the search items group
     2. be sure to enable the search items by toggling the checkbox, which might possibly still be disabled 
     3. enable the search filter(s) which are going to be used by toggling their respective checkbox(es)
     4. interact with the search filter(s) to set the desired parameter(s)
     5. finally, press the `Search Geonode` button

     This whole interaction should be simplified to only:
     
     1. expand the search items group
     2. interact with the search filter(s) to set the desired parameter(s)
     3. finally, press the `Search Geonode` button

   In order for the search to be possible without having to use a checkbox to enable/disable all search filters and also not having to use a checkbox for each individual filter, we need to:

     - Add a blank option in the `Keywords` which shall be the default
     - Add a blank option in the `TopicCateogry` which shall be the default
     - the `start` and `end` date time widgets should also be null by default

4. I'm OK with not having the spatial extent implemented just yet, but I guess the spatial extent filtering should be. Unless the GeoNode API is not able to cope with it?

2021-02-10 13:13 UTC, ricardogsilva commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +            )
This implementation makes the search filter mutually exclusive, which is not the way to go. We want them to be additive instead, so a user is able to, for example, search for a `vector` layer with `abc` in its title.

2021-02-10 13:13 UTC, ricardogsilva commented on src/qgis_geonode/gui/geonode_source_select_provider.py
> +        self.search_keywords()
see my comment above about this function

2021-02-10 13:13 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            metadata.setCategories([geonode_resource.category['identifier']])
Category is annotated in `GeonodeResource` as being a string. Here you are using it as a dict, so maybe there is some bug  in the code where we parse the category and the GeoNode API is being leaked out of the `GeonodeResource` class. Please fix this.

2021-02-12 19:12 UTC, Samweli commented on src/qgis_geonode/gui/search_result_widget.py
> +            metadata.setCategories([geonode_resource.category['identifier']])
The way I see it, is we should change the annotation to dict because that is what the API currently provide. Are you okay with this?

2021-02-12 19:47 UTC, Samweli commented
> 4\. I'm OK with not having the spatial extent implemented just yet, but I guess the spatial extent filtering should be

Sorry I haven't quite get you here @ricardogsilva, do you want to implement spatial extent filtering?

2021-02-12 23:27 UTC, ricardogsilva commented on src/qgis_geonode/gui/search_result_widget.py
> +            metadata.setCategories([geonode_resource.category['identifier']])
No. 

The response of the API must not be leaked out of the API client class onto the caller. Otherwise we cannot implement other versions of the GeoNode API. As an example, for the legacy API client, the result is an XML element. If we were to sometimes return a dict and sometimes return an XML element, then the caller of this code would need to check for all possibilities, which would be a mess. And what if a future version of the API returns a dict with a different schema? Or if it returns a string?

The overall strategy is in the API client class we parse whatever the API returns into something that makes sense for the caller of this code. In the case of the topic category, what we care about is the category text, nothing more. So this must be parsed into a simple string.

2021-02-12 23:29 UTC, ricardogsilva approved these changes
Thanks for your work.

I found that somethings were still in need of work so I pushed a commit into this PR with the changes. This was mainly to move us forward, as I don't want to spend more time with additional review cycles on this issue.

Seems good to merge now

2021-02-12 23:29 UTC, merged